#!/usr/bin/env bash
python LAL-Parser/src_joint/main.py train \
 --model-path-base LAL-Parser/models/joint_xlnet_clean_large_3_layers_no_resdrop_lambda \
  --epochs 100 \
 --use-xlnet \
 --use-tags \
 --const-lada 0.5 \
 --dataset ptb \
 --embedding-path /kaggle/input/glove6b100dtxt/glove.6B.100d.txt \
 --model-name joint_xlnet_clean_large_3_layers_no_resdrop_lambda \
 --checks-per-epoch 4 \
 --num-layers 3 \
 --learning-rate 0.00005 \
 --batch-size 100 \
 --eval-batch-size 20 \
 --subbatch-max-tokens 1000 \
 --train-ptb-path LAL-Parser/data/02-21.10way.clean \
 --dev-ptb-path LAL-Parser/data/22.auto.clean \
 --dep-train-ptb-path LAL-Parser/data/ptb_train_3.3.0.sd.clean \
 --dep-dev-ptb-path LAL-Parser/data/ptb_dev_3.3.0.sd.clean \
 --lal-d-kv 128 \
 --lal-d-proj 128 \
 --no-lal-resdrop
